my_string = input('введите произвольный текст: ')
print('длинна символов: ', len(my_string))
print('строка в верхнем регистре: ', my_string.upper())
print('строка в нижнем регистре: ', my_string.lower())
my_string.replace(' ', '')
print('первый символ строки: ', my_string[0])
print('последний символ строки:', my_string[len(my_string) - 1])
